import type { EmotionColorKey } from "./emotion";

/** Emotion fossil - condensed emotion diary entry */
export interface Fossil {
  id: string;
  conversationId: string;
  inscription: string;
  userNote?: string;
  emotionTags: string[];
  primaryEmotion: string;
  emotionColor: EmotionColorKey;
  emotionIntensity: number;
  timeDisplay: string;
  createdAt: Date;
}

/** Landscape data point for emotion terrain visualization */
export interface LandscapeDataPoint {
  date: string;
  emotion: string;
  intensity: number;
  fossilId: string;
  color: EmotionColorKey;
}

/** Landscape insight generated by AI */
export interface LandscapeInsight {
  text: string;
  period: "week" | "month" | "all";
}

/** Echo letter - letter to future self */
export interface EchoLetter {
  id: string;
  content: string;
  emotionBackground: string;
  status: "pending" | "opened" | "expired";
  writtenAt: Date;
  writtenAtDisplay: string;
  openAt: Date;
  daysRemaining: number;
  openedAt?: Date;
  retrospective?: string;
}
